SimonJinaphant/Discovr

app/src/main/java/org/cpen321/discovr/EventsSubscribedFragment.java, app/src/main/java/org/cpen321/discovr/MainActivity.java, app/src/main/java/org/cpen321/discovr/SQLiteDBHandler.java, app/src/main/java/org/cpen321/discovr/SingleEventFragment.java, app/src/main/res/drawable/star_toggle_off.xml, app/src/main/res/drawable/star_toggle_on.xml, app/src/main/res/layout/fragment_events_subscribed.xml, app/src/main/res/layout/fragment_single_event.xml
=> displays single event and enables unsubscribing from previously subscribed events

app/src/main/java/org/cpen321/discovr/MainActivity.java
Cleaned up and refactored repeated code when switching between fragments.
=> Refactored fragment changer code

app/src/main/java/org/cpen321/discovr/MainActivity.java
=> Route is removed on new queries

app/src/main/java/org/cpen321/discovr/AllEventsFragment.java, app/src/main/java/org/cpen321/discovr/EventsSubscribedFragment.java
=> Redo animation effect from event list to single event

app/src/main/java/org/cpen321/discovr/BuildingInformation.java, app/src/main/java/org/cpen321/discovr/GeoJsonParser.java, app/src/main/java/org/cpen321/discovr/MainActivity.java, app/src/main/java/org/cpen321/discovr/SQLiteDBHandler.java, app/src/main/java/org/cpen321/discovr/model/BuildingInformation.java
getBuildings method - takes in InputStream and returns a list of BulidingInformation objects
=> Building db

app/src/main/java/org/cpen321/discovr/MainActivity.java, app/src/main/java/org/cpen321/discovr/MapViewFragment.java, app/src/main/res/layout/app_bar_main.xml, app/src/main/res/layout/fragment_map_view.xml
1. Created a custom map fragment to hold the map view
1. Moved functions that deal with map functionalities into the map fragment
1. Refactored MainActivity
=> Custom map fragment

app/src/main/java/org/cpen321/discovr/MainActivity.java
Added cleo's list of courses fragment for demo purposes
=> Added cleo's courses fragment to drawer

app/src/main/java/org/cpen321/discovr/MainActivity.java
=> Keyboard now dissapears on drawer closing and drawer opening

app/src/main/java/org/cpen321/discovr/MainActivity.java
=> Keyboard closes on search submission

app/build.gradle, app/src/androidTest/java/org/cpen321/discovr/MainActivityTest.java, app/src/main/java/org/cpen321/discovr/MainActivity.java, app/src/main/java/org/cpen321/discovr/MapViewFragment.java
Main Change:
Tests for MainActivity has been added and all dependencies for testing are managed on gradle.
Random change:
Reduced map zoom time to 3 seconds.
=> Adding instrumented test

app/src/main/java/org/cpen321/discovr/AllEventsFragment.java, app/src/main/java/org/cpen321/discovr/EventsSubscribedFragment.java, app/src/main/java/org/cpen321/discovr/GeoJsonParser.java, app/src/main/java/org/cpen321/discovr/MainActivity.java, app/src/main/java/org/cpen321/discovr/MapViewFragment.java, app/src/main/java/org/cpen321/discovr/SQLiteDBHandler.java, app/src/main/java/org/cpen321/discovr/SingleEventFragment.java, app/src/main/java/org/cpen321/discovr/model/Building.java, app/src/main/res/layout/fragment_all_event.xml, app/src/main/res/layout/fragment_single_event.xml
Fixes to Buildings DB code
Changes to Buildings model
Added ability to search by building name / code,
fixes #14
=> Integration with Buildings DB 

app/src/main/java/org/cpen321/discovr/GeoJsonParser.java, app/src/main/java/org/cpen321/discovr/MainActivity.java, app/src/main/java/org/cpen321/discovr/SingleEventFragment.java
Still need to integrate better location pin dropping and better search function
fixes #75
=> Moves map to event location when event selected

app/src/main/java/org/cpen321/discovr/CoursesFragment.java
no more courses are loaded to local database if the courses already exist
fixed #119
=> issue#119 is fixed 

app/src/main/AndroidManifest.xml, app/src/main/java/org/cpen321/discovr/AllEventsFragment.java, app/src/main/java/org/cpen321/discovr/CoursesFragment.java, app/src/main/java/org/cpen321/discovr/MainActivity.java, app/src/main/java/org/cpen321/discovr/MyCustomSuggestionProvider.java, app/src/main/java/org/cpen321/discovr/SQLiteDBHandler.java, app/src/main/java/org/cpen321/discovr/SingleBuildingFragment.java, app/src/main/res/layout/fragment_courses.xml, app/src/main/res/xml/searchable.xml
Autocomplete feature for searching buildings
Handles intent when suggestion is pressed
Formatting details to Building Fragment & All Events Fragment
closes #64
=> Autocomplete for querying buildings

app/src/main/java/org/cpen321/discovr/EventClientManager.java, app/src/main/java/org/cpen321/discovr/model/EventInfo.java, app/src/test/java/org/cpen321/discovr/EventClientManagerTest.java
Added tests for EventClientManage and equality for EventInfo
=> Added tests and created equality checking for EventInfo

app/src/main/java/org/cpen321/discovr/EventClientManager.java, app/src/main/java/org/cpen321/discovr/MainActivity.java, app/src/main/java/org/cpen321/discovr/MapViewFragment.java
Changes done from final demo: 
- Changed event database source
- Upcoming events are actually upcoming events
- Construction overlay added
=> Final demo

app/src/main/java/org/cpen321/discovr/CoursesFragment.java, app/src/main/java/org/cpen321/discovr/SQLiteDBHandler.java, app/src/main/java/org/cpen321/discovr/parser/CalendarFileParser.java, app/src/test/java/org/cpen321/discovr/SQLiteDBHandlerTest.java
Database testing finished for events.
TODO: Courses and Buildings database tests
Closes #140
=> Adding tests for Event database

app/src/main/java/org/cpen321/discovr/fragment/CoursesFragment.java, app/src/main/java/org/cpen321/discovr/fragment/partial/CoursePartialFragment.java, app/src/main/res/layout/fragment_single_course.xml, app/src/main/res/values/colors.xml
- show courses for the current term only
- implement partial course frag
- move the map the course location
- can get the building by its partial name or keyword only but not its full name (bug)
#125 and #123 fixed
=> Show course location

app/src/main/assets/simplebuildings.geojson, app/src/main/java/org/cpen321/discovr/MainActivity.java, app/src/main/java/org/cpen321/discovr/MyCustomSuggestionProvider.java, app/src/main/java/org/cpen321/discovr/SQLiteDBHandler.java, app/src/main/java/org/cpen321/discovr/fragment/CoursesFragment.java, app/src/main/java/org/cpen321/discovr/utility/AlertUtil.java, app/src/main/res/xml/searchable.xml
- Course notification is now on MainActivity rather than the ListAllCourses fragment
- Load the courses from local ical files once the app is opened
- No pause happens if you click on the ListAllCourses
- The course notification will bring up only when you have this class today and it will starts in 10 mins
closes #151 and #131
=> Course refactor

app/src/main/java/org/cpen321/discovr/SQLiteDBHandler.java, app/src/test/java/org/cpen321/discovr/SQLiteDBHandlerTest.java
- course tests for local database completed
close #141
=> course tests added

app/src/main/java/org/cpen321/discovr/MainActivity.java
=> Added Show Bus toolbar title

app/src/main/java/org/cpen321/discovr/fragment/partial/TransitPartialFragment.java, app/src/main/java/org/cpen321/discovr/parser/TransitParser.java
=> Fixed transit schedule for weekdays

app/src/main/java/org/cpen321/discovr/MainActivity.java, app/src/main/java/org/cpen321/discovr/SQLiteDBHandler.java
App was crashing if ical did not exist
=> Hotfix for nonexistent ical for courses

app/src/main/java/org/cpen321/discovr/MainActivity.java, app/src/main/java/org/cpen321/discovr/fragment/EventsFragment.java, app/src/main/java/org/cpen321/discovr/fragment/MapViewFragment.java
Initial fix removes functionality of returning to the "All Events" and "Subscribed Events" page on backpress.
=> Hotfix for fragment stacking v2

app/src/main/java/org/cpen321/discovr/MainActivity.java, app/src/main/java/org/cpen321/discovr/fragment/EventsFragment.java, app/src/main/java/org/cpen321/discovr/fragment/EventsSubscribedFragment.java, app/src/main/java/org/cpen321/discovr/fragment/partial/CoursePartialFragment.java, app/src/main/java/org/cpen321/discovr/fragment/partial/EventPartialFragment.java
=> Event marker doubling up fix

app/src/main/java/org/cpen321/discovr/EventClientManager.java
When your web hosting free trial expires right before the due date...
=> Update URL to switch from expired cloud subscription
